services:
  - type: web
    name: paws-and-pause
    runtime: node
    rootDir: sjd_y_sus_amigos/sjd_y_sus_amigos
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
